random_state: 42
test_size: 0.2

paths:
  features: data/raw/elliptic_txs_features.csv
  classes:  data/raw/elliptic_txs_classes.csv
  edgelist: data/raw/elliptic_txs_edgelist.csv
  registry_dir: models/registry
  artifacts_dir: models/artifacts
  reports_dir: reports

features:
  drop: ["txId", "time_step", "class"]

imbalance:
  smote: true

models:
  use_logreg: true
  use_decisiontree: true
  use_randomforest: true
  use_xgboost: true

scoring: f1
threshold_tuning: false

plots:
  feature_importance_top_k: 25